name: weekly-tests

on:
  workflow_dispatch:
  schedule:
    - cron: 0 13 * * 1

jobs:
  test_states:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        salt: [3006, 3007]
        os: [20.04, 22.04]
        state:
          - sift.packages.python2
          - sift.packages.python3
          - sift.tests.gift
          - sift.config.user.pdfs
        include:
          - os: 20.04
            code: focal
          - os: 22.04
            code: jammy
    container:
      image: docker://ghcr.io/ekristen/cast-tools/saltstack-tester:${{ matrix.code }}-${{ matrix.salt }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: test-state
        run: |
          salt-call -l info --file-root . --local --retcode-passthrough --state-output=mixed state.sls ${{ matrix.state }} pillar="{sift_user: root}"
